### ISSUE TITLE
unable to activate

### ISSUE THREAD

**Issue by lvnilesh** [litefeel/writing-on-github#11]
```
#2 /var/www/html/wp-admin/plugins.php(43): activate_plugin('writing-on-gith...', 'https://domain.com', false)
#3 {main}
  thrown in /var/www/html/wp-content/plugins/writing-on-github/writing-on-github.php on line 111
[20-Mar-2018 03:28:34 UTC] PHP Fatal error:  Uncaught Error: Class 'Writing_On_GitHub_Admin' not found in /var/www/html/wp-content/plugins/writing-on-github/writing-on-github.php:111
Stack trace:
#0 /var/www/html/wp-content/plugins/writing-on-github/writing-on-github.php(20): Writing_On_GitHub->__construct()
#1 /var/www/html/wp-admin/includes/plugin.php(1897): include('/var/www/html/w...')
#2 /var/www/html/wp-admin/plugins.php(172): plugin_sandbox_scrape('writing-on-gith...')
#3 {main}
  thrown in /var/www/html/wp-content/plugins/writing-on-github/writing-on-github.php on line 111
```

**Comment by litefeel** [comment]
@lvnilesh 
Thanks for your feedback.
Please tell me some of the following information.
1. What is your php version?
2. Do you use nginx or apache?
3. How to install this plugin.

**Comment by lvnilesh** [comment]
1. php version
```
php -v
PHP 7.2.3 (cli) (built: Mar 14 2018 14:01:21) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
```
2. nginx or apache
```
Wordpress running in a pod using wordpress:4.9.4-php7.2-apache in a kubernetes cluster with nginx-ingress
```

3. How did I install?
```
cd /var/www/html/wp-content/plugins
git clone https://github.com/litefeel/writing-on-github.git
chown -R www-data:www-data writing-on-github
```

**Comment by litefeel** [comment]
@lvnilesh 
This repository lacks some dependencies, so **don't clone this repository from git.**
Please install it from [wordpress](https://wordpress.org/plugins/writing-on-github/)

**Comment by lvnilesh** [comment]
Can't use that method. I need it to be git based. What would it take?

**Comment by litefeel** [comment]
Why git?
You can download `writing-on-github.xxxx.zip` from [wordpress](https://wordpress.org/plugins/writing-on-github/).

If you must use origin source code, you can build it manually.
1. install [composer](https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx)
2. update composer call `composer self-update`
3. install dependencies call  `composer install`
4. now, it can work.
