### ISSUE TITLE
删除Github文章是否会同步删除Wordpress文章呢？

### ISSUE THREAD

**Issue by banpie** [litefeel/writing-on-github#17]
Hi：

今天再重新测试插件的时候，发现我把Github的文章删除后，但是wordpress的文章还保留着，不知道这个是不是默认的配置呢？

我已经尝试了：
1. 从github导入；
2. 强制从github导入；

**Comment by litefeel** [comment]
Sorry so late.
Fixed it on version 1.10
https://wordpress.org/plugins/writing-on-github/
