### ISSUE TITLE
使用 GitHub 更改博文时会误生成评论

### ISSUE THREAD

**Issue by xuan-w** [litefeel/writing-on-github#19]
在本地修改博文，push到GitHub以更新时，有一定概率会在对应文章下出现错误评论。

评论作者为被更改的文章的标题，评论联系方式不是电子邮箱而是这篇文章的静态链接地址，来源 IP 为本机。目前在几十次 push 中总共出现了六次这种情况。

这六次事件的共同点是，被修改的博文都添加了指向站内其它博客的超链接。且生成的垃圾评论的评论内容就是超链接所在的句子。不知道在解析 markdown 中的站内超链接的时候是不是有什么 bug。

原本以为是站外垃圾评论，后来发现来源IP就是博客自己，而且这个评论联系方式也并不是一个电子邮箱，显然不是正常 WordPress 访问生成的。

WordPress 版本 5.3.2 英文版。安装的是 WordPress 插件商店里的最新版 1.9。安装了 Jetpack 以实现 markdown 转换。Jetpack 版本 8.3。WordPress 版本过高，所以官方商店里没有 WP markdown 可用。

我猜也可能是 Jetpack 的 bug

**Comment by litefeel** [comment]
你好，
这不是Jetpack的bug， 这是pingback，是wordpress的正常机制。
如果不想接收pingback可以在评论里取消掉。
![image](https://user-images.githubusercontent.com/1288575/76150668-f9083d00-60e7-11ea-88d1-12f3070fbcc0.png)
