### ISSUE TITLE
Line #48 in /lib is not valid

### ISSUE THREAD

**Issue by hellojennifertran** [litefeel/writing-on-github#2]
`public function fetch_all_supported( bool $force = false ) {`

Value "false" isn't a valid which doesn't allow plugin to activate.

I'm using Wordpress v. 4.8

**Comment by hellojennifertran** [comment]
There are a few references where "false" isn't valid. Change it to "null" to get the plugin to activate.

Here are the locations:
database.php - line 48
controller.php - line 54
export.php - line 34

**Comment by litefeel** [comment]
@hellojennifertran 
Thanks for your feedback.
what is your php version?

**Comment by litefeel** [comment]
@hellojennifertran 
I fixed it, please update it. thanks.
