### ISSUE TITLE
在markdown中插入图片

### ISSUE THREAD

**Issue by xuan-w** [litefeel/writing-on-github#20]
根据 README.md 的说法，有一个目录 images/ 用于保存所有图片。
但是我在修改博文并使用 `![](../../images/xxx.png)` 的方式引用，在github中可以正常显示图片，在 wordpress 中没有显示图片。

似乎图片并没有被上传到 wordpress 当中去。

这是否是一个计划中还没有实现的功能呢？

**Comment by litefeel** [comment]
images/下的文件会上传到  `wp-content/uploads/writing-on-github/images/` 下， 如果本身已经添加了markdown插件，就会自动修正到正确的路径

**Comment by xuan-w** [comment]
我检查了一下，图片是被正常上传上去的。但是生成的图片链接是不大对的。

举例来说，我的博文链接是 `domain/yyyy/mm/dd/title`，插入 `![](../../images/xxx.png)` 的话，在 git hub 里可以显示，但是生成的博文的图片链接只是截掉了博文 permanent link 里的两级，变成了 `domain/yyyy/mm/images/xxx.png`，自然是无法显示的。

必须写成 `![](../../../../wp-content/uploads/writing-on-github/images/xxx.png)` 才能正确显示。

这样的话，在markdown里使用相对地址插图片就没有什么优点了，既不能直接预览，写起来也哆嗦，还不如直接用 WordPress 自己的图片系统的图片地址。经常 rsync 备份一下图片也就可以了

我使用的 markdown 插件是 jetpack。

**Comment by litefeel** [comment]
已经调整了images目录下文件的路径问题，更新到最新版就可以了

**Comment by litefeel** [comment]
之前是支持 /images/。。。这样的绝对路径，这个在markdown里也能预览
现在又支持了 ../images/。。。这样的相对路径。
