### ISSUE TITLE
GitHub import/sync to Wordpress not triggered by commit which results in 404 error

### ISSUE THREAD

**Issue by hellojennifertran** [litefeel/writing-on-github#3]
GitHub import/sync to Wordpress not triggered by commit which results in 404 error.

1. I have to go to Wordpress and manually click "Import from GitHub"
2. Because the sync isn't updated via commit, the links that reference GitHub .md file doesn't work

Ex: I update a "hello-world.md" in GitHub with a new title called "hello-new-world.md" and when I go to Wordpress to click on the post, it's still saved as the old revision "hello world" which links me to a 404 page as it should be updated to "hello new world".

What, exactly, is the expected behavior of this plugin? Is it supposed to be a manual import, or should the sync be triggered when a commit is made?

Still, mad props to yourself and mAAdhaTTah. I'm a big fan of this GitHub<-->Wordpress plugin.

-jt

**Comment by litefeel** [comment]
@hellojennifertran
Thanks for your feedback.

The filename of github and the post name of wordpress is different.
You can use tag of `post_name` to change post name of wordpress.
like this:

~~~yml
---
....
post_name: hello-new-world
...
---
Post goes here.
~~~


https://github.com/litefeel/writing-on-github#importing-from-github


But, Now has an issues #4 
change post_name in github, it cannot automodity tag of link in github.

so, If you want display correct link, must `force export to github` in wordpress

**Comment by litefeel** [comment]
@hellojennifertran 
I has fixed this bug. please update, thanks.

**Comment by hellojennifertran** [comment]
Thanks for all the fixes this weekend. I'm still wondering what the behavior of this plugin is supposed to be. Should a post created/updated from GitHub trigger a sync to go into Wordpress when a commit is made? Currently, I have to manually click the "Import from GitHub" link.

**Comment by litefeel** [comment]
@hellojennifertran 
Now, I know that why are you cannot trigger a sync to wordpress. 
Please see here https://github.com/litefeel/writing-on-github#configuring-the-plugin

You have to create a WebHook within your repository with the provided callback URL and callback secret.

Now, It can automatically sync to wordpress when you push a commit to github.
