### ISSUE TITLE
How do you remove GitHub link reference in Wordpress pages?

### ISSUE THREAD

**Issue by hellojennifertran** [litefeel/writing-on-github#5]
How do you remove GitHub link reference in Wordpress pages?

It makes sense to create Wordpress posts in GitHub, but doesn't make sense with Wordpress pages since I leverage a layout builder plugin to create my pages and need to be able to access the Wordpress page.

Thanks in advance for your help!

-jt

**Comment by litefeel** [comment]
@hellojennifertran 
Thanks for your feedback.
I do not know which layout builder plugin you are using.
I install **Beaver Builder Plugin (Lite Version)**. 
Create a page and public it.
I can enter layout builder via page.

like this.

![image](https://user-images.githubusercontent.com/1288575/29299028-7b93cbee-819e-11e7-8f4b-e0543b19193a.png)

**Comment by hellojennifertran** [comment]
You know what, good point. I was concerned about the code syncing from GitHub and messing up the updates made in page builder during import, but it doesn't.

Thanks! 👍
