### ISSUE TITLE
How does GitHub markdown get converted when displayed on Wordpress?

### ISSUE THREAD

**Issue by hellojennifertran** [litefeel/writing-on-github#6]
I'm having issues with GitHub markdown being displayed on Wordpress correctly. The markdown doesn't convert to HTML even after trying WP Markdown plugin. What do you currently use to convert your GitHub markdown?

Thanks for any help!

JT

**Comment by litefeel** [comment]
@hellojennifertran 
Thanks for your feedback.

Now. I use [wp-parsedown](https://wordpress.org/plugins/wp-parsedown/) to renderer markdown to html.

But. I suggest you that use other markdown plugin like *WP Markdown*.
Some markdown plugin render markdown when display post,
Other markdown plugins render markdown when save post.
For performance reasons, I suggest you use other plugins like *WP Markdown*.

So the base workflow:
1. Activity markdown plugin
2. Enable **Don't export content** option from Writing on Github
3. Writing post on Github or create post from wordpress


Now, How to convert the existing wordpress post into html?
You can edit every post on GitHub, example add new line into every post on github.

I will add a button to force the import from github in the next release.

thanks.

**Comment by hellojennifertran** [comment]
Awesome! That resolved the issue with Markdown conversion. Thanks so much.
I appreciate your prompt response and updates to this plugin. Great work so far!

JT
