### ISSUE TITLE
How do you automate GitHub import to Wordpress?

### ISSUE THREAD

**Issue by hellojennifertran** [litefeel/writing-on-github#7]
I configured the GitHub webhook, but I still have to manually click "Import from GitHub." How can we automate this so that after a commit is made to the master branch, it triggers an update to Wordpress?

JT

**Comment by litefeel** [comment]
Hi. @hellojennifertran 
I guess you didn't set up your webhooks correctly.

so. please see the response in the following path.
Settings > Webhooks > Click the link > See last response,
like this:

![image](https://user-images.githubusercontent.com/1288575/29736311-8ae9608a-8a32-11e7-8c21-b4449528e9a0.png)

**Comment by aharonium** [comment]
I'm having trouble with this too. Some more documentation in how to set up the webhook correctly might anticipate this issue. (There is no "Webhooks" option in my Personal Settings menu.)

**Comment by aharonium** [comment]
I looked at the FAQ and wasn't clear which one of these options I should set in the webhook settings. I'm thinking this is fine:

![image](https://user-images.githubusercontent.com/855510/29946638-22ae70e6-8e74-11e7-8d95-b6a646ee4388.png)

**Comment by litefeel** [comment]
@aharonium Yes.  it's correct.
