### ISSUE TITLE
wordpress与GitHub同步问题

### ISSUE THREAD

**Issue by CoolMusk** [litefeel/writing-on-github#8]
Hello，请问使用插件后，WordPress多久与GitHub同步一次？只能手动操作插件么？

**Comment by CoolMusk** [comment]
提示 {"success":false,"data":[{"code":"invalid_headers","message":"\u9a8c\u8bc1 webhook \u4e8b\u4ef6\u5931\u8d25\u3002"}]}
message信息是：验证webhook事件失败

**Comment by litefeel** [comment]
@CoolMusk 在github中修改或在wordpress中修改，会立刻同步，修改的那篇文章，如果需要导出到导入，需要手动操作


验证webhook事件失败 
注意要选json
![image](https://user-images.githubusercontent.com/1288575/36709075-02bbbba2-1bb1-11e8-94dc-8d32a4489c11.png)

**Comment by CoolMusk** [comment]
![image](https://user-images.githubusercontent.com/31949746/36709343-62bb9de6-1bb2-11e8-9a71-9dc4c42ab151.png)
![image](https://user-images.githubusercontent.com/31949746/36709365-78fff76e-1bb2-11e8-84a3-1e2be4fafaac.png)
![image](https://user-images.githubusercontent.com/31949746/36709376-83e8c2dc-1bb2-11e8-9c81-3c47b82aa385.png)

感谢回复，我设置的是json格式的。但是还是遇到这个问题。
步骤是先在WordPress上设置好授权和密码，然后再来github项目上添加webhook。

但是我手动导入导出是正常的。
每次github更新，webhook都提示 “验证webhook失败”。
@litefeel 请问有其他项可供检查吗？

**Comment by litefeel** [comment]
@CoolMusk  
该插件只支持 ping 和 push 事件， 如果不是这两个事件，就会提示  验证webhook事件失败。

你看看收到 验证webhook事件失败 的时候的， request 信息，看看是什么 事件。

**Comment by CoolMusk** [comment]
@litefeel 
header信息为：
```
Request URL: http://www.xxxxx.com/wp-admin/admin-ajax.php?action=wogh_push_request
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/7a06a51
X-GitHub-Delivery: f28630b2-1b99-11e8-85cb-367f84553e6a
X-GitHub-Event: push
X-Hub-Signature: sha1=xxxxxxxxx
```
event信息是push事件。

另外ping事件也是报验证webhook事件失败。
```
Request URL: http://www.xxxx.com/wp-admin/admin-ajax.php?action=wogh_push_request
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/7a06a51
X-GitHub-Delivery: e1762910-1b6e-11e8-88c1-75dc7d804cd4
X-GitHub-Event: ping
X-Hub-Signature: sha1=xxxxxxxxxxxxxxxxxxx
```

报错信息为：
```
{"success":false,"data":[{"code":"invalid_headers","message":"\u9a8c\u8bc1 webhook \u4e8b\u4ef6\u5931\u8d25\u3002"}]}
```

**Comment by litefeel** [comment]
是最新版本的插件吗

**Comment by CoolMusk** [comment]
@litefeel 
你好，是最新版本插件。
![image](https://user-images.githubusercontent.com/31949746/36722086-93ab3760-1be7-11e8-8988-baff09639070.png)

WordPress版本是 4.9.4

**Comment by litefeel** [comment]
这就奇怪了， **验证webhook事件失败** 只能是事件类型有问题。
你再试试修改一个github上的post看看

**Comment by CoolMusk** [comment]
@litefeel  
你好，post我修改了，header跟之前类似。
```
Request URL: http://www.XXXX.com/wp-admin/admin-ajax.php?action=wogh_push_request
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/7a06a51
X-GitHub-Delivery: 2b021d84-1bc7-11e8-99ec-9a2977cf50a8
X-GitHub-Event: push
X-Hub-Signature: sha1=XXXXXXXX
```

返回还是失败的。
请问你觉得有什么地方我需要去自验的么？

**Comment by CoolMusk** [comment]
@litefeel  
你好，查看了你插件中`controller.php`中关于push error的处理代码。因为我不会PHP，是否我可以本地对你代码进行调试？模拟push到我webhook回调地址的请求？

**Comment by litefeel** [comment]
这个不好本地调试的

**Comment by devbanpie** [comment]
我也是手动导入可以成功的，但是如果是push 更新的话，提示如下错误：
```

Request URL: https://xxx.com/wp-admin/admin-ajax.php?action=wpghs_sync_request
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/7a71d82
X-GitHub-Delivery: 3ea8cdf6-1ea1-11e8-9b15-10b09e0e2e32
X-GitHub-Event: push
X-Hub-Signature: sha1=65ae2b65a74b397c42422147a4557eaf5ca5e41d
```

Reponse 是Invalid Http response 400：

```
Cache-Control: no-cache, must-revalidate, max-age=0
Connection: Upgrade, close
Content-Length: 1
Content-Type: text/html; charset=UTF-8
Date: Sat, 03 Mar 2018 05:10:56 GMT
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Referrer-Policy: same-origin
Server: Apache
Transfer-Encoding: chunked
Upgrade: h2
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/7.1.5
X-Robots-Tag: noindex
```

**Comment by litefeel** [comment]
@devbanpie 尝试先把github里的所有内容删掉，然后重新导出到github，再修改github的文章看看是否可以正常同步到wordpress

**Comment by devbanpie** [comment]
@litefeel 感谢回复。我尝试如下操作：

1. 清空Github 所有文章；
2.  清空Wordpress 所有文章；
2. 重新复制文章到Github 仓库并Push；
3. Webhook 还是出现同样的400错误；
3. 在Wordpress 插件里面点击`import from Github`
4. 文章可以从Github 同步过来，但是在Wordpress点击编辑文章，跳转到Github 修改后，无法同步回到Wordpress的文章中。
5. 切换到Wordpress的插件中提示，`Import from GitHub failed with error: Method PUT to endpoint https://api.github.com/repos/banpie/bpblog/contents/_posts/2018-03-02-%e6%b5%8b%e8%af%95.md failed with error: Invalid request. "sha" wasn't supplied.`

**Comment by devbanpie** [comment]
这边所有的Push都是红色的条，我的服务器是Cent OS，PHP 7.0，难道是阿里云和Github API通信的问题？

![2018-03-03 9 44 33](https://user-images.githubusercontent.com/14344140/36934963-3f3ede0a-1f2c-11e8-81f7-9a90de6b7582.jpg)

**Comment by litefeel** [comment]
@devbanpie 
~~~
Import from GitHub failed with error: Method PUT to endpoint https://api.github.com/repos/banpie/bpblog/contents/_posts/2018-03-02-%e6%b5%8b%e8%af%95.md failed with error: Invalid request. "sha" wasn't supplied.
~~~
这个表示wordpress 已经成功的链接到了GitHub。
wordpres想要新建一个文件，但是GitHub上已经存在改文件了。
你确认下，是否真的已经存在该文件了。

**Comment by devbanpie** [comment]
@litefeel 谢谢反馈。我尝试删除Webhooks 在新建1个重新同步，现在正常了。

另外想请问一下我之前使用的是Jekyll 的默认YAML格式，如下：

```
title: "文章名称"
date: 2018-03-01
permalink: "article-name"
published: true
```

发现只有是使用以下的才能成功显示。

```
post_title: '文章名称'
post_name: "article-name"
layout: post
published: true_or_false
```

是否是插件只支持这个固定的YAML呢？

**Comment by devbanpie** [comment]
还有一个问题，重制Webhook同步后，但是只能同步15篇文章（重复测试），然后Debug 信息就出现了：

```
- Controller::pull_posts() ：同步机制已触发，正在进行导入/导出。
- 无法验证密匙。
- Method DELETE to endpoint https://api.github.com/repos/banpie/bpblog/contents failed with error: Not Found
```

**Comment by CoolMusk** [comment]
@devbanpie  你好，请问你的“验证WebHook失败”的问题，是通过重新建立仓库，重新导入导出来解决的？

**Comment by devbanpie** [comment]
@CoolMusk 我是删除Webhook，在新建一个解决的。另外，想请问你的Post_date 同步会出现问题吗？

**Comment by CoolMusk** [comment]
@devbanpie 你指的是post_date 会被WordPress的同步操作更新掉？

**Comment by devbanpie** [comment]
@CoolMusk 对啊，你不会吗？比如一开始的Github _posts文件夹中的文件YAML标注`2017-01-01 08:00:00`,一旦import后，仓库自己会做一个move的操作，把文档的YAML重写了，日期也修改成新的日期。

**Comment by CoolMusk** [comment]
@devbanpie  会遇到，但并不是所有文章，只是最近更新的文章才会出现这个问题。比方post_date是2018-03-01，于今日2018-03-07更新后，同步过去，会变化，我这边是概率性，我也没看出原因。需要插件开发者帮忙了。@litefeel

**Comment by devbanpie** [comment]
@litefeel @CoolMusk 我也反馈给源插件开发者了，但是没有什么反馈。我一次性只能同步17篇，所以剩余的post不会被重写，但是一旦在点击import，没有同步的部分还是会被重写。

**Comment by CoolMusk** [comment]
@devbanpie [捂脸] 如果你PHP OK的话，可以研究一下，我最近打算有空看下源码。或者要思考其他的方式来解决这个问题。

**Comment by devbanpie** [comment]
@CoolMusk 然而我并不太懂代码 [叹气]，求大神带路 😄

**Comment by CoolMusk** [comment]
@devbanpie  如果我找到解决办法，我就留言给你。。

**Comment by litefeel** [comment]
@devbanpie  @CoolMusk 
关于YAML格式，目前是这样的，不是完全与Jekyll兼容。
关于日期被重写的问题，请到 https://github.com/litefeel/writing-on-github/issues/9 讨论
关于只能同步15篇文章的问题，请到 https://github.com/litefeel/writing-on-github/issues/10 讨论

**Comment by litefeel** [comment]
@CoolMusk 更新到最新版本，看看还会出现 **验证webhook事件失败** 的问题吗

**Comment by CoolMusk** [comment]
@litefeel  你好，更新了最新的插件后，在github上重建了webhook。
抛错如下：
`{"success":false,"data":[{"code":"invalid_headers","message":"Failed to validate webhook event: ."}]}
`

**Comment by CoolMusk** [comment]
@litefeel  你好，想问下，如何在yaml中带入文章的特色图片的设置呀？

**Comment by litefeel** [comment]
@CoolMusk 
你将 `writing-on-github/lib/request.php`  替换为下面的文件，再试试会输出什么。
https://raw.githubusercontent.com/litefeel/writing-on-github/f1dad785760d21b7ead4c53f01b6c87889d226d0/lib/request.php

yaml里现在不支持特色图片

**Comment by CoolMusk** [comment]
@litefeel  
替代后，返回如下：
```
getallheaders
array(8) {
  ["Host"]=>
  string(14) "www.233lab.com"
  ["Accept"]=>
  string(3) "*/*"
  ["User-Agent"]=>
  string(23) "GitHub-Hookshot/7a71d82"
  ["X-GitHub-Event"]=>
  string(4) "ping"
  ["X-GitHub-Delivery"]=>
  string(36) "bda8d720-2515-11e8-9534-4a836e6a0bdf"
  ["content-type"]=>
  string(16) "application/json"
  ["X-Hub-Signature"]=>
  string(45) "sha1=569fad020b4705fa27d515896bff5b3c49bafcb0"
  ["Content-Length"]=>
  string(4) "6182"
}
{"success":false,"data":[{"code":"invalid_headers","message":"Failed to validate webhook event: ."}]}
```

**Comment by litefeel** [comment]
@CoolMusk 请下载最新的版本，已经解决了不能同步的问题。

**Comment by CoolMusk** [comment]
@litefeel  感谢~重新试了一下，问题已经解决了。打Call。
