### ISSUE TITLE
从GitHub中导入时，GitHub中post_date信息被意外修改

### ISSUE THREAD

**Issue by litefeel** [litefeel/writing-on-github#9]
比如一开始的Github _posts文件夹中的文件YAML标注2017-01-01 08:00:00,一旦import后，仓库自己会做一个move的操作，把文档的YAML重写了，日期也修改成新的日期。

**Comment by devbanpie** [comment]
这一块的问题是原本的机制吗？还是说Bug？

**Comment by litefeel** [comment]
我看了代码，之前不支持修改 post_date 数据的。

**Comment by litefeel** [comment]
@devbanpie 我想到一个修改post_date的规则，你看怎么样。

1. 如果存在正常值的post_date字段， 则应用该日期。
2. 否则使用 now。

当有新文章的时候，不设置post_date，则自动使用最新日期。
当更新已有文章的时候，需要删除已有的 post_date 字段，否则不会自动更新日期。

**Comment by devbanpie** [comment]
@litefeel 是的，我觉得这个才是正确的逻辑。我想通常来说使用使用这个插件的，大约3种情况：
1. github 和wordpress两边都没有文章：使用最新的日期没有问题；
2. gihtub有文章，wordpress没有文章：导入wordpress应该使用github文章中已有的post_date，如果没有那么久使用now；
3. github 没有文章，wordpress 有文章：这种情形需要先导出到github，导入到文章的post_date 应该是和wordpress的发布日期相同的。

**Comment by litefeel** [comment]
我明天改下，发个新版本

**Comment by litefeel** [comment]
已经改好并发了新版本了

**Comment by devbanpie** [comment]
测试已经成了，但是有一点是同步的时候，每一篇文章会被重新移动，通常是move的动作，但是内容没有修改，这样比如有25篇文章新同步，就会有25条新的commit，这个是正常的吧？

**Comment by litefeel** [comment]
@devbanpie 
因为现在md文件名的格式是 日期+名字，所以日期更新了，文件名也会更新。
文件名更新的机制是，先删除原有的文件，再新增文件。

**Comment by devbanpie** [comment]
@litefeel 感谢回复。目前是日期的问题没有被强制更改，但是在日期没有更新的情况下，文件夹也会被自动更新和原来一样的，这个不应该是这样吧？比如说原本的文件名是`2018-01-01-how-to-do.md`，同步开始后，github会把这个文件在移动到相同的位置，但是文件名还是`2018-01-01-how-to-do.md`，然后生成1条move操作的commit。

**Comment by litefeel** [comment]
@devbanpie 
md文件名没变的情况下，不应该会有move 操作的， 你看看我的测试地址 https://github.com/litefeel/testwpsync2

**Comment by devbanpie** [comment]
@litefeel 有的，你在 [这里](https://github.com/devbanpie/blog) 试一下

**Comment by litefeel** [comment]
@devbanpie 
我看了下commit 记录， move都是正常的，改名是2条commit，他们的message都是move
1. 删除旧文件
2. 创建新文件

**Comment by devbanpie** [comment]
@litefeel move 正常那就可以了，就是一开始文章多，同步的时候太多commit了，如果没有修改的不commit，修改了才commit 会好一些。总之，非常感谢。

**Comment by litefeel** [comment]
@devbanpie  我看到好多都是中文文件名修改为英文文件名了， 所以需要move

**Comment by devbanpie** [comment]
@litefeel 我今天重新在测试了一下，无论文件名之前是中文还是英文都是会重新做一次commit，比如有200个文档，同步就会commit 200次，主要是因为同步的时候，ymal会被修改，比如增加了ID、author等字段，这个是本身的机制吗？

如果是，有一点不方便的时候，如果未来修改了URL或者说是增加了标签之类的，应该是就无法双向同步了吧。

**Comment by litefeel** [comment]
修改url是要重新导出到GitHub，所以需要commit。
只要是github和wordpress都正常，并且webhook也正常，那么不论哪边做修改，都会同步到另一边。
